[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
# my_project = "7HB2ioJ5bFu2K5xnqxbSampSdCHdToftNzEJJCzkybUx"
my_project = "G8wijYorkKGjFkwNQ8zoUdWR67NoZ3Jwc3t4Q2dFJREb"

[programs.devnet]
# my_project = "7HB2ioJ5bFu2K5xnqxbSampSdCHdToftNzEJJCzkybUx"
my_project = "G8wijYorkKGjFkwNQ8zoUdWR67NoZ3Jwc3t4Q2dFJREb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
